# auto
# spring.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect

# manual
## connection db
### via jboss datasource
# app.datasource.primary.jndi-name=java:jboss/datasources/PortalDigitDS

### set datasource
app.datasource.primary.driver-class=org.hibernate.dialect.Oracle12cDialect
app.datasource.primary.url=jdbc:oracle:thin:@10.243.139.104:1521:JALINSIT
app.datasource.primary.username=esbappjalin
app.datasource.primary.password=esbappjalin
app.datasource.primary.primary.hikari.connection-timeout=30000
app.datasource.primary.primary.hikari.maximum-pool-size=5

##- note
app.data.lpad.enabled=true 
app.ldap.repositories.enabled=true

## LDAP
### ldap 1 password incorrect
app.ldap.urls=ldap://supporting.devmandiri.co.id:389
app.ldap.base=DC=supporting,DC=devmandiri,DC=co,DC=id
app.ldap.sub-base=
app.ldap.username=wbo.user1
app.ldap.password=12345

#### ldap 2 password correct
app.ldap2.urls=ldap://supporting.devmandiri.co.id:389
app.ldap2.base=DC=supporting,DC=devmandiri,DC=co,DC=id
app.ldap2.sub-base=
app.ldap2.username=wbo.user1
app.ldap2.password=7pR,6E0d

app.ldap.principal=supporting
app.ldap.bypass-username=super,superapprove,2023070186,int.super,dimas.prasetia,erongt1,indra79
app.ldap.enabled=true

## url domain
app.firewall.AllowedHosts=localhost;web.digit.corp.bankmandiri.co.id;10.204.146.37;10.204.146.48;10.254.146.46;10.254.146.37

## Redis (isnt used)
# spring.session.store-type=redis
# spring.session.redis.namespace=portaldigit:session
# spring.redis.sentinel.nodes=10.243.235.13:26379,10.243.235.14:26379
# spring.redis.sentinel.master=mymaster
# spring.redis.password=Mandiri123

# redis.pool.maxTotal=50000
# redis.pool.minIdle=10
# redis.pool.maxIdle=20000
# redis.pool.testOnBorrow=true
# redis.pool.testOnReturn=true
# spring.data.redis.repositories.enabled=false


app.httpclient.timeout.ms=30000