# - Environment -> dev,sit,uat,pt,prod
spring.profiles.active=dev
spring.application.name=base web
server.servlet.context-path=/base
server.port=8080
server.error.path=/error
# server.error.include-message=always
# spring.main.allow-bean-definition-overriding=true

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=true

# - Logging
# debug=true
# logging.level.web=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
# logging.level.org.hibernate.sql=error

#logging.level.=error
# logging.level.org.hibernate.type=trace
# logging.level.org.springframework.security=DEBUG
# logging.level.org.springframework.web=DEBUG
# spring.thymeleaf.cache=false
# spring.thymeleaf.enabled=true
# spring.thymeleaf.prefix=classpath:/templates/
# spring.thymeleaf.suffix=.html

#
info.app.spring-boot.version=@project.version@