# auto
# spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# manual
## connection db
### set datasource
app.datasource.primary.driver-class=org.hibernate.dialect.MySQL8Dialect
app.datasource.primary.url=jdbc:mysql://localhost:3306/esbappjalin
app.datasource.primary.username=root
app.datasource.primary.password=root
app.datasource.primary.primary.hikari.connection-timeout=30000
app.datasource.primary.primary.hikari.maximum-pool-size=5